
# Auto-generated by Interface Designer
#
# WARNING: Any manual changes made to this file will be lost when generating constraints.

# Efinity Interface Designer SDC
# Version: 2025.1.110
# Date: 2025-06-06 15:11

# Copyright (C) 2013 - 2025 Efinix Inc. All rights reserved.

# Device: T120F324
# Project: sync_fifo
# Timing Model: C3 (final)
